### ISSUE TITLE
Zoom for pictures is not available !! 

### ISSUE THREAD

**Issue by alirahimifachr** [krassowski/Anki-Zoom#12]
if there is a picture and Text, it just zoom in the Text  

maybe it can be helpful

from PIL import Image

// Image.open() can also open other image types
img = Image.open("some_random_image.jpg")
// WIDTH and HEIGHT are integers
resized_img = img.resize((WIDTH, HEIGHT))
resized_img.save("resized_image.jpg")

// OR

im = Image.open('image.jpg')  
im = im.resize((w, h))

**Comment by alirahimifachr** [comment]
maybe it can be helpful

from PIL import Image

# Image.open() can also open other image types
img = Image.open("some_random_image.jpg")
# WIDTH and HEIGHT are integers
resized_img = img.resize((WIDTH, HEIGHT))
resized_img.save("resized_image.jpg")

# OR

im = Image.open('image.jpg')  
im = im.resize((w, h))

**Comment by saranpan** [comment]
++++
